## Importing the libraries and dataset

In [27]:
#Import libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [28]:
#Importing the food delivery app (Zomato) dataset
zomato = pd.read_csv('zomato.csv')
zomato.head(2)

address            name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...           Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...  Spice Elephant   

  online_order book_table   rate votes                           phone  \
0          Yes        Yes  4.1/5   775  080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5   787                    080 41714161   

       location      rest_type  \
0  Banashankari  Casual Dining   
1  Banashankari  Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   

                         cuisines approx_cost(for two people) listed_in(type)  
0  North Indian, Mughlai, Chinese                         800          Buffet  
1     Chinese, North Indian, Thai                         800          Buffet

In [29]:
zomato.shape,zomato.size

((56252, 13), 731276)

In [30]:
zomato.describe()

address           name online_order book_table   rate  votes  \
count           56235          56236        56233      56194  48414  56174   
unique          13397          11914         2639       2902   2877   5195   
top      ('Rated 4.0'   ('Rated 4.0'          Yes         No    NEW      0   
freq              942            300        30444      45268   2208  10027   

                phone location    rest_type     dish_liked      cuisines  \
count           54956    56126        55914          28027         56049   
unique          17712     2920         2961           8067          5553   
top      ('Rated 4.0'      BTM  Quick Bites   ('Rated 4.0'  North Indian   
freq              412     5125        19132            407          2913   

       approx_cost(for two people) listed_in(type)  
count                        55731           51642  
unique                        2879            2783  
top                            300        Delivery  
freq                          7576           24317

In [31]:
zomato.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56252 entries, 0 to 56251
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   address                      56235 non-null  object
 1   name                         56236 non-null  object
 2   online_order                 56233 non-null  object
 3   book_table                   56194 non-null  object
 4   rate                         48414 non-null  object
 5   votes                        56174 non-null  object
 6   phone                        54956 non-null  object
 7   location                     56126 non-null  object
 8   rest_type                    55914 non-null  object
 9   dish_liked                   28027 non-null  object
 10  cuisines                     56049 non-null  object
 11  approx_cost(for two people)  55731 non-null  object
 12  listed_in(type)              51642 non-null  object
dtypes: object(13)
memory usage: 5.6

## Task 1: Renaming and selecting colums and their data types
Only these columns are allowed in the dataset:<br>
1.Id 2.Name 3.online_order 4.book_table 5.rating 6.votes 7.location 8.rest_type 9.dish_liked 10.cuisines 11.approx_cost 12.type

In [32]:
zomato['Id'] = zomato.index
zomato.columns

Index(['address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'Id'],
      dtype='object')

In [33]:
allowed_columns_order = ['Id','name','online_order','book_table','rate','votes','location','rest_type','dish_liked',
                        'cuisines','approx_cost(for two people)','listed_in(type)']

cleaned_zomato = zomato[allowed_columns_order]
cleaned_zomato.columns = ['Id','Name','online_order','book_table','rating','votes','location','rest_type','dish_liked',
                        'cuisines','approx_cost','type']
cleaned_zomato.head(2)

Id            Name online_order book_table rating votes      location  \
0   0           Jalsa          Yes        Yes  4.1/5   775  Banashankari   
1   1  Spice Elephant          Yes         No  4.1/5   787  Banashankari   

       rest_type                                         dish_liked  \
0  Casual Dining  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Casual Dining  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   

                         cuisines approx_cost    type  
0  North Indian, Mughlai, Chinese         800  Buffet  
1     Chinese, North Indian, Thai         800  Buffet

In [34]:
cleaned_zomato.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56252 entries, 0 to 56251
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            56252 non-null  int64 
 1   Name          56236 non-null  object
 2   online_order  56233 non-null  object
 3   book_table    56194 non-null  object
 4   rating        48414 non-null  object
 5   votes         56174 non-null  object
 6   location      56126 non-null  object
 7   rest_type     55914 non-null  object
 8   dish_liked    28027 non-null  object
 9   cuisines      56049 non-null  object
 10  approx_cost   55731 non-null  object
 11  type          51642 non-null  object
dtypes: int64(1), object(11)
memory usage: 5.2+ MB


## Task 2: Dealing with null values

In [35]:
# percentage of null values
(cleaned_zomato.isna().sum() / len(cleaned_zomato))*100

Id               0.000000
Name             0.028443
online_order     0.033777
book_table       0.103107
rating          13.933727
votes            0.138662
location         0.223992
rest_type        0.600868
dish_liked      50.175994
cuisines         0.360876
approx_cost      0.926189
type             8.195264
dtype: float64

In [36]:
#Dropping nullvalues from name column
cleaned_zomato['Name'].dropna(inplace=True)

#Replacing null values with 'NA' except for rating, votes, approx_cost, where its replaced with 0
for i in cleaned_zomato.columns:
    if i in ['rating', 'votes', 'approx_cost']:
        cleaned_zomato[i].fillna(0,inplace=True)
    else:
        cleaned_zomato[i].fillna('NA',inplace=True)
        
cleaned_zomato.isna().sum()

Id              0
Name            0
online_order    0
book_table      0
rating          0
votes           0
location        0
rest_type       0
dish_liked      0
cuisines        0
approx_cost     0
type            0
dtype: int64

## Task 3: Identifying duplicate data

In [37]:
#There are no duplicates
print(cleaned_zomato.duplicated(subset=['Name','location']).sum())

cleaned_zomato.drop_duplicates(subset=['Name','location'],keep = 'last',inplace=True)

40291


## Task 4: Text cleaning

In [38]:
for i in cleaned_zomato.columns:
    print(i)
    print(cleaned_zomato[i].value_counts(normalize=True),'\n')

Id
29       0.000063
47923    0.000063
47886    0.000063
47889    0.000063
47890    0.000063
           ...   
27890    0.000063
27891    0.000063
27892    0.000063
27893    0.000063
56251    0.000063
Name: Id, Length: 15961, dtype: float64 

Name
 ('Rated 4.0'                   0.012781
 ('Rated 5.0'                   0.009523
 ('Rated 3.0'                   0.005513
 ('Rated 1.0'                   0.002757
 ('Rated 3.5'                   0.002318
                                  ...   
Le Spice Restaurant             0.000063
Aroma Spice                     0.000063
My China                        0.000063
Navami Kitchen                  0.000063
The Nest - The Den Bengaluru    0.000063
Name: Name, Length: 11915, dtype: float64 

online_order
Yes                                                                                                                                                                                                                                                 

In [39]:
cleaned_zomato.size

191532

In [40]:
for i in cleaned_zomato.columns:
    if i!= 'Id':
        cleaned_zomato = cleaned_zomato[cleaned_zomato[i].str.contains('RATED|Rated')==False]

In [41]:
cleaned_zomato.size

115944

## Task 5: Unique value check and irrelevant value handling

In [42]:
cleaned_zomato['online_order'].unique()

array(['No', 'Yes', 'tawa ke veg',
       ' classy. Communiti should be your go to place if you are in Bangalore. They have the best micro brewery!! The vibe is so positive and welcoming. Located in the prime location',
       ' Mochar Chop', ' Food: 3.5/5'], dtype=object)

In [43]:
cleaned_zomato = cleaned_zomato[cleaned_zomato['online_order'].str.contains('Yes|No')==True]
cleaned_zomato['online_order'] = cleaned_zomato['online_order'].str.strip()
cleaned_zomato['online_order'].unique()

array(['No', 'Yes'], dtype=object)

In [44]:
cleaned_zomato['rating'].unique()

array(['3.3/5', '3.7/5', '3.6/5', '2.9/5', 'NEW', '3.8/5', '3.2/5',
       '4.1/5', '3.9/5', '3.4/5', '4.2/5', '3.1/5', '4.0/5', '3.5/5',
       '3.0/5', '2.6/5', '4.7/5', '4.3/5', '2.8/5', '2.4/5', '2.7/5',
       '2.5/5', '4.6/5', '4.5/5', '4.4/5', '4.8/5', '3.9 /5', '4.0 /5',
       '4.1 /5', '2.9 /5', '3.7 /5', '2.8 /5', '3.8 /5', '4.2 /5',
       '3.5 /5', '3.4 /5', '-', '3.6 /5', '3.3 /5', '3.2 /5', '3.1 /5',
       '2.3/5', '4.9/5', '4.4 /5', '4.5 /5', '3.0 /5', '4.3 /5', '2.7 /5',
       '2.2/5', '2.6 /5', '4.7 /5', '4.6 /5', '2.3 /5', '2.5 /5',
       '2.4 /5', '4.8 /5', '4.9 /5', '2.0 /5', '2.1 /5', '1.8 /5',
       '2.2 /5'], dtype=object)

In [45]:
cleaned_zomato['rating'] = cleaned_zomato['rating'].str.replace('/5','')
cleaned_zomato['rating'][cleaned_zomato['rating']=='-']
cleaned_zomato['rating'] = cleaned_zomato['rating'].replace({'NEW' : '0', '-' : '0'})
cleaned_zomato['rating'] = cleaned_zomato['rating'].str.strip()
cleaned_zomato['rating'] = cleaned_zomato['rating'].astype('float64')
cleaned_zomato['rating'].unique()

array([3.3, 3.7, 3.6, 2.9, 0. , 3.8, 3.2, 4.1, 3.9, 3.4, 4.2, 3.1, 4. ,
       3.5, 3. , 2.6, 4.7, 4.3, 2.8, 2.4, 2.7, 2.5, 4.6, 4.5, 4.4, 4.8,
       2.3, 4.9, 2.2, 2. , 2.1, 1.8])

In [46]:
cleaned_zomato['approx_cost'].unique()

array(['550', '850', '500', '700', '300', '100', '200', '400', '650',
       '600', '800', '450', '150', '1,000', '250', '350', '80', '750',
       '1,600', '900', '950', '1,100', '1,200', '1,300', '2,000', '70',
       '3,000', '1,500', '2,200', '1,400', '2,500', '1,800', '560',
       '1,700', '1,350', '1,050', '180', '1,250', '40', '230', '130',
       '2,100', '2,300', '3,200', '4,000', '3,400', '2,400', '4,100',
       '5,000', '3,700', '2,700', '4,500', '240', '3,500', '6,000',
       '1,900', '120', '2,600', '1,650', '50', '199', '2,800', '330',
       '1,450'], dtype=object)

In [47]:
cleaned_zomato['approx_cost'] = cleaned_zomato['approx_cost'].str.replace(',','')
cleaned_zomato['approx_cost'] = cleaned_zomato['approx_cost'].str.strip()
cleaned_zomato['approx_cost'] = cleaned_zomato['approx_cost'].astype('int64')
cleaned_zomato['approx_cost'].unique()

array([ 550,  850,  500,  700,  300,  100,  200,  400,  650,  600,  800,
        450,  150, 1000,  250,  350,   80,  750, 1600,  900,  950, 1100,
       1200, 1300, 2000,   70, 3000, 1500, 2200, 1400, 2500, 1800,  560,
       1700, 1350, 1050,  180, 1250,   40,  230,  130, 2100, 2300, 3200,
       4000, 3400, 2400, 4100, 5000, 3700, 2700, 4500,  240, 3500, 6000,
       1900,  120, 2600, 1650,   50,  199, 2800,  330, 1450], dtype=int64)

In [48]:
cleaned_zomato['votes'].unique()

array(['23', '679', '6', ..., '1218', '1003', '1094'], dtype=object)

In [49]:
cleaned_zomato['votes'] = cleaned_zomato['votes'].astype('int64')
cleaned_zomato['votes'].unique()

array([  23,  679,    6, ..., 1218, 1003, 1094], dtype=int64)

In [50]:
cleaned_zomato.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9658 entries, 29 to 56251
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Id            9658 non-null   int64  
 1   Name          9658 non-null   object 
 2   online_order  9658 non-null   object 
 3   book_table    9658 non-null   object 
 4   rating        9658 non-null   float64
 5   votes         9658 non-null   int64  
 6   location      9658 non-null   object 
 7   rest_type     9658 non-null   object 
 8   dish_liked    9658 non-null   object 
 9   cuisines      9658 non-null   object 
 10  approx_cost   9658 non-null   int64  
 11  type          9658 non-null   object 
dtypes: float64(1), int64(3), object(8)
memory usage: 980.9+ KB


## Task 6: Cleaning and exporting zomato dataset

In [51]:
#Removing special characters from names (only keeping letters A-Z and a-z)
cleaned_zomato['Name'] = cleaned_zomato['Name'].str.replace('[^A-Za-z]','')

#Exporting cleaned dataset to a new csv file called 'cleanedzomato.csv'
cleaned_zomato.to_csv('cleanedzomato.csv')
print('Successfully exported')

Successfully exported
